### ISSUE TITLE
TypeScript typings issue

### ISSUE THREAD

**Issue by sannysoft** [manuelmhtr/countries-and-timezones#38]
Getting the following error with TypeScript 4.3.5:
`Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier`

**Comment by manuelmhtr** [comment]
Hi @benj-dobs, @kherock
I'm not a TS expert, any thoughts would be appreciated 🙏

**Comment by benj-dobs** [comment]
Interesting, not sure why you're getting it and I'm not. I'll look into it.

**Comment by kherock** [comment]
@benj-dobs Do you have `"skipLibCheck": true` in your tsconfig? It's because the inline json from the rollup json loader doesn't have a `'declare'`modifier.

**Comment by benj-dobs** [comment]
Yep @kherock you've nailed it.

I spent a bit of time yesterday trying to configure Rollup to generate the files a different way, but I'm not too familiar with Rollup and I couldn't make it work. I can look into it again at a later date but I'm not totally sure when I'll get around to it.

If we don't have a better option, I guess we could replace the JSON `const` object type with something more general.

**Comment by manuelmhtr** [comment]
Hi all,
This problem is fixed in `v3.2.2` with the temporary solution of adding the `declare` keyword with a bash script (https://github.com/manuelmhtr/countries-and-timezones/pull/40). In case `rollup-plugin-dts` gets fixed (@kherock) we could move to a cleaner and definitive solution.

@benj-dobs feel free to modify or close https://github.com/manuelmhtr/countries-and-timezones/pull/39 in case there's something we should keep from it.
