### ISSUE TITLE
deprecating timezones

### ISSUE THREAD

**Issue by iwpnd** [manuelmhtr/countries-and-timezones#42]
Hi 👋 

what's your take on deprecating timezones in this library? 

While I see you have removed some deprecated ones with `v3.0.0`, I can also see that some still remain even though they're deprecated (`Poland`, `America/Grenada` and many more). The latter are almost exclusively linked to the current canonical correct name. 
What is your source of truth here?

**Comment by manuelmhtr** [comment]
Hi @iwpnd!
My main source is [IANA news](https://data.iana.org/time-zones/tzdb/NEWS),
then [Paul Eggert's database](https://raw.githubusercontent.com/eggert/tz/main/zone1970.tab)
and finally adding aliases using [moment data](https://raw.githubusercontent.com/moment/moment-timezone/master/data/packed/latest.json).

I think the problem is moment, I guess it adds a lot of aliases for backward compatibility.
In your experience, is there any other source I should consider? Any suggestion is very welcome.

**Comment by iwpnd** [comment]
Hey, the latter seems to be the root cause for deprecated time zones in your collection. `moment-timezone` is still on IANA 2021a, while 2021b was released in September '21.
I always resort to wikipedia to be honest. [This tz database](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) maintained over there is on point and even lists what's canonical and what's deprecated.

**Comment by manuelmhtr** [comment]
Sounds good. I'll work this week to update the data.

**Comment by iwpnd** [comment]
Thank you 🙏

**Comment by manuelmhtr** [comment]
Hi @iwpnd, thanks. I'm almost done. I updated the data with 2021c IANA database and included all deprecated timezones (some users might find them useful as well) BUT they won't be returned by the current API by default, I'll add a `deprecated` option to return them when required.
I hope to release this version by Sunday 🤞

**Comment by manuelmhtr** [comment]
Hi @iwpnd, it's done!!
Version [3.3.0](https://github.com/manuelmhtr/countries-and-timezones/releases/tag/v3.3.0) matches Wikipedia, it resulted to be really accurate and better organized than the other sources.

Also, added the `deprecated` option but by default you won't notice any deprecated timezone.

Feedback is welcome 👍
