### ISSUE TITLE
Missing Timezone for getTimezonesForCountry

### ISSUE THREAD

**Issue by acommodari** [manuelmhtr/countries-and-timezones#54]
Hello when we use the `getTimezonesForCountry` api with the country Bouvet Island (BV) we receive an empty array.

**Comment by manuelmhtr** [comment]
Hi @acommodari, thanks for reporting the problem.
The Bouvet Island (`BV`) and Heard Island and McDonald Islands (`HM`) have been removed since they are dependent territories, nobody lives there, and they don't have official timezones.

The change is available in [v3.5.0](https://github.com/manuelmhtr/countries-and-timezones/releases/tag/v3.5.0).
