### ISSUE TITLE
Swapped UTC and DST offsets for Europe/Dublin, Africa/Casablanca, Africa/El_Aaiun

### ISSUE THREAD

**Issue by loongyh** [manuelmhtr/countries-and-timezones#55]
`utcOffset` should be 0 and `dstOffset` should be 60 for `Europe/Dublin`, `Africa/Casablanca`, `Africa/El_Aaiun`

**Comment by manuelmhtr** [comment]
Hi @loongyh thanks for reporting the problem. However, it turns out those timezones observe a "negative DST". That is, they use their standard time during summer and apply a negative transition during winter.

Take Dublin as an example. The legislation indicates +1:00 is [their standard time](https://www.irishstatutebook.ie/eli/1968/act/23/enacted/en/html) and +0:00 [during winter](https://www.irishstatutebook.ie/eli/1971/act/17/enacted/en/html).
