### ISSUE TITLE
Error: Cannot find module './data'

### ISSUE THREAD

**Issue by nlopin** [manuelmhtr/countries-and-timezones#7]
Hi! 

After update to version 2, my app started to fail with the error:

```
Module not found: Error: Can't resolve './data' in 'projectname/node_modules/countries-and-timezones/src'
```

**Comment by manuelmhtr** [comment]
Hi @nlopin,
That's weird, it should work. However, **I would not recommend to require `/data`**.

Since [v2.0.0](https://github.com/manuelmhtr/countries-and-timezones/blob/21f4f8a98ca70079e31b5c08a67364dc98a4b3fa/CHANGELOG.md) data is a much simpler object (to make it 72% lighter), therefore some duplicated data was removed and object keys are not descriptive. However you can get a similar object by doing:
```js
const ct = require('countries-and-timezones');
const data = {
  countries: ct. getAllCountries(),
  timezones: ct. getAllTimezones()
};
```

**Comment by nlopin** [comment]
I do not require `/data` it is required internally in the library. I'll investigate more

**Comment by manuelmhtr** [comment]
I see. Apparently is not a good practice to load json files with `require`.
Could you try changing the file `projectname/node_modules/countries-and-timezones/src/index.js`

From:
```js
const data = require('./data');
```
To 
```js
const data = require('./data.json');
```

If that works, could you tell me you node version and operative system?

Meanwhile I'll check the best practices to require json files.

**Comment by manuelmhtr** [comment]
According to [documentation](https://nodejs.org/docs/latest-v8.x/api/modules.html#modules_require), require is designed to support JSON files as long as `.json` extension is used.

[v2.0.3](https://github.com/manuelmhtr/countries-and-timezones/pull/10) should fix the issue.

**Comment by nlopin** [comment]
Thank you, 2.0.3 fixes the issue
